# テンソル
スカラーを複数の次元に並べたもの

In [10]:
import numpy as np

# スカラー
a = 1.5
a

1.5

In [11]:
# ベクトル
b = np.array([1,2,3])
b

array([1, 2, 3])

In [12]:
# 行列
c = np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
# 3階のテンソル
d = np.array([[[0,1,2],
              [3,4,5],
              [7,7,8]],
              
              [[8,7,6],
              [5,4,3],
              [2,1,0]]])
d

array([[[0, 1, 2],
        [3, 4, 5],
        [7, 7, 8]],

       [[8, 7, 6],
        [5, 4, 3],
        [2, 1, 0]]])